configure: src/autoconf.h.in configure.in
	autoconf

src/autoconf.h.in: 
	autoheader

clean:
	rm -rf autom4te.cache configure config.log config.cache Makefile src/autoconf.h config.status buildnum.data src/autoconf.h.in
	
