
default: configure src/autoconf.h
	./configure
	
configure: configure.in
	autoconf

src/autoconf.h: src/autoconf.h.in
	autoheader

clean:
	rm -rf autom4te.cache configure config.log config.cache Makefile src/autoconf.h config.status buildnum.data
	
