/*
 * Recycle times for 'standard' VRT
 */
#define VRT_CL_AC10		25	/* CL.AC/10 */
#define VRT_CL_AC2		12	/* CL.AC/2 */
#define VRT_CL_AC20		30	/* CL.AC/20 */
#define VRT_CL_AC5		20	/* CL.AC/5 */
#define VRT_CL_APOD		30	/* CL.A-Pod */
#define VRT_CL_AMS		10	/* CL.Anti-MissileSystem */
#define VRT_CL_ARROWIV		60	/* CL.ArrowIVSystem */
#define VRT_CL_GR		30	/* CL.GaussRifle */
#define VRT_CL_LBX10		25	/* CL.LB10-XAC */
#define VRT_CL_LBX2		15	/* CL.LB2-XAC */
#define VRT_CL_LBX20		30	/* CL.LB20-XAC */
#define VRT_CL_LBX5		20	/* CL.LB5-XAC */
#define VRT_CL_LRM10		20	/* CL.LRM-10 */
#define VRT_CL_LRM15		25	/* CL.LRM-15 */
#define VRT_CL_LRM20		30	/* CL.LRM-20 */
#define VRT_CL_LRM5		15	/* CL.LRM-5 */
#define VRT_CL_MG		 7	/* CL.MachineGun */
#define VRT_CL_NARC		30	/* CL.NarcBeacon */
#define VRT_CL_SRM2		15	/* CL.SRM-2 */
#define VRT_CL_SRM4		15	/* CL.SRM-4 */
#define VRT_CL_SRM6		15	/* CL.SRM-6 */
#define VRT_CL_SSRM2		15	/* CL.StreakSRM-2 */
#define VRT_CL_SSRM4		15	/* CL.StreakSRM-4 */
#define VRT_CL_SSRM6		15	/* CL.StreakSRM-6 */
#define VRT_CL_UAC10		25	/* CL.UltraAC/10 */
#define VRT_CL_UAC2		12	/* CL.UltraAC/2 */
#define VRT_CL_UAC20		30	/* CL.UltraAC/20 */
#define VRT_CL_UAC5		20	/* CL.UltraAC/5 */
#define VRT_IS_AC10		25	/* IS.AC/10 */
#define VRT_IS_AC2		12	/* IS.AC/2 */
#define VRT_IS_AC20		30	/* IS.AC/20 */
#define VRT_IS_AC5		20	/* IS.AC/5 */
#define VRT_IS_AMS		10	/* IS.Anti-MissileSystem */
#define VRT_IS_ARROWIV		60	/* IS.ArrowIVSystem */
#define VRT_IS_GR		30	/* IS.GaussRifle */
#define VRT_IS_LBX10		25	/* IS.LB10-XAC */
#define VRT_IS_LRM10		20	/* IS.LRM-10 */
#define VRT_IS_LRM15		25	/* IS.LRM-15 */
#define VRT_IS_LRM20		30	/* IS.LRM-20 */
#define VRT_IS_LRM5		15	/* IS.LRM-5 */
#define VRT_IS_LONGTOM		60	/* IS.LongTom */
#define VRT_IS_MG		 7	/* IS.MachineGun */
#define VRT_IS_NARC		30	/* IS.NarcBeacon */
#define VRT_IS_SRM2		15	/* IS.SRM-2 */
#define VRT_IS_SRM4		15	/* IS.SRM-4 */
#define VRT_IS_SRM6		15	/* IS.SRM-6 */
#define VRT_IS_SNIPER		60	/* IS.Sniper */
#define VRT_IS_SSRM2		15	/* IS.StreakSRM-2 */
#define VRT_IS_THUMPER		60	/* IS.Thumper */
#define VRT_IS_UAC5		20	/* IS.UltraAC/5 */
#define VRT_PC_BLAZER		10	/* PC.Blazer */
#define VRT_PC_CROSSBOW		15	/* PC.Crossbow */
#define VRT_PC_FLRIFLE		10	/* PC.FederatedLongRifle */
#define VRT_PC_FLAMER		 7	/* PC.FlamerPistol */
#define VRT_PC_GYROSLUG		10	/* PC.GyroslugRifle */
#define VRT_PC_HGGUN		10	/* PC.HeavyGyrojetGun */
#define VRT_PC_ILRIFLE		10	/* PC.IntekLaserRifle */
#define VRT_PC_LRIFLE		10	/* PC.LaserRifle */
#define VRT_PC_PLPISTOL		10	/* PC.PulseLaserPistol */
#define VRT_PC_PLRIFLE		10	/* PC.PulseLaserRifle */
#define VRT_PC_SMG		 5	/* PC.SMG */
#define VRT_PC_SHOTGUN		15	/* PC.Shotgun */
#define VRT_PC_SPISTOL		10	/* PC.SternsnachtPistol */
#define VRT_PC_SLPISTOL		 7	/* PC.SunbeamLaserPistol */
#define VRT_PC_ZHRIFLE		10	/* PC.ZeusHeavyRifle */
#define VRT_IS_ELRM5		30	/* IS.ELRM-5 */
#define VRT_IS_ELRM10		30	/* IS.ELRM-10 */
#define VRT_IS_ELRM15		30	/* IS.ELRM-15 */
#define VRT_IS_ELRM20		30	/* IS.ELRM-20 */
#define VRT_IS_LR_DFM5		15	/* IS.LR_DFM-5 */
#define VRT_IS_LR_DFM10		20	/* IS.LR_DFM-10 */
#define VRT_IS_LR_DFM15		25	/* IS.LR_DFM-15 */
#define VRT_IS_LR_DFM20		30	/* IS.LR_DFM-20 */
#define VRT_IS_SR_DFM2		15	/* IS.SR_DFM-2 */
#define VRT_IS_SR_DFM4		15	/* IS.SR_DFM-4 */
#define VRT_IS_SR_DFM6		15	/* IS.SR_DFM-6 */
#define VRT_IS_SSRM4		15	/* IS.StreakSRM-4 */
#define VRT_IS_SSRM6		15	/* IS.StreakSRM-6 */
#define VRT_IS_TBOLT5		20	/* IS.Thunderbolt-5 */
#define VRT_IS_TBOLT10		20	/* IS.Thunderbolt-10 */
#define VRT_IS_TBOLT15		30	/* IS.Thunderbolt-15 */
#define VRT_IS_TBOLT20		30	/* IS.Thunderbolt-20 */
#define VRT_IS_CAC2		12	/* IS.CaselessAC/2 */
#define VRT_IS_CAC5		20	/* IS.CaselessAC/5 */
#define VRT_IS_CAC10		25	/* IS.CaselessAC/10 */
#define VRT_IS_CAC20		30	/* IS.CaselessAC/20 */
#define VRT_IS_HAC2		12	/* IS.HyperAC/2 */
#define VRT_IS_HAC5		20	/* IS.HyperAC/5 */
#define VRT_IS_HAC10		25	/* IS.HyperAC/10 */
#define VRT_IS_LBX2		15	/* IS.LB2-XAC */
#define VRT_IS_LBX5		20	/* IS.LB5-XAC */
#define VRT_IS_LBX20		30	/* IS.LB20-XAC */
#define VRT_IS_UAC2		12	/* IS.UltraAC/2 */
#define VRT_IS_UAC10		25	/* IS.UltraAC/10 */
#define VRT_IS_UAC20		30	/* IS.UltraAC/20 */
#define VRT_IS_MRM10		20	/* IS.MRM-10 */
#define VRT_IS_MRM20		30	/* IS.MRM-20 */
#define VRT_IS_MRM30		30	/* IS.MRM-30 */
#define VRT_IS_MRM40		30	/* IS.MRM-40 */
#define VRT_CL_ERLL		20	/* CL.ERLargeLaser */
#define VRT_CL_ERML		15	/* CL.ERMediumLaser */
#define VRT_CL_ERPPC		25	/* CL.ERPPC */
#define VRT_CL_ERSL		10	/* CL.ERSmallLaser */
#define VRT_CL_FLAMER		10	/* CL.Flamer */
#define VRT_CL_LL		25	/* CL.LargeLaser */
#define VRT_CL_LPL		23	/* CL.LargePulseLaser */
#define VRT_CL_ML		20	/* CL.MediumLaser */
#define VRT_CL_MPL		18	/* CL.MediumPulseLaser */
#define VRT_CL_PPC		30	/* CL.PPC */
#define VRT_CL_SL		15	/* CL.SmallLaser */
#define VRT_CL_SPL		13	/* CL.SmallPulseLaser */
#define VRT_IS_ERLL		25	/* IS.ERLargeLaser */
#define VRT_IS_ERPPC		30	/* IS.ERPPC */
#define VRT_IS_FLAMER		10	/* IS.Flamer */
#define VRT_IS_LL		25	/* IS.LargeLaser */
#define VRT_IS_LPL		25	/* IS.LargePulseLaser */
#define VRT_IS_ML		20	/* IS.MediumLaser */
#define VRT_IS_MPL		20	/* IS.MediumPulseLaser */
#define VRT_IS_PPC		30	/* IS.PPC */
#define VRT_IS_SL		15	/* IS.SmallLaser */
#define VRT_IS_SPL		15	/* IS.SmallPulseLaser */
#define VRT_PC_SWORD		 3	/* PC.Sword */
#define VRT_PC_VIBROBLADE	 3	/* PC.Vibroblade */
#define VRT_IS_ERML		20	/* IS.ERMediumLaser */
#define VRT_IS_ERSL		15	/* IS.ERSmallLaser */
#define VRT_IS_LGR		20	/* IS.LightGaussRifle */
#define VRT_IS_XLPL		27	/* IS.X-LargePulseLaser */
#define VRT_IS_XMPL		22	/* IS.X-MediumPulseLaser */
#define VRT_IS_XSPL		17	/* IS.X-SmallPulseLaser */
#define VRT_IS_HFLAMER		15	/* IS.HeavyFlamer */
#define VRT_IS_HMG		 7	/* IS.HeavyMachineGun */
#define VRT_IS_LAC2		12	/* IS.LightAC/2 */
#define VRT_IS_LAC5		20	/* IS.LightAC/5 */
#define VRT_CL_ERLPL		30	/* CL.ERLargePulseLaser */
#define VRT_CL_ERMPL		30	/* CL.ERMediumPulseLaser */
#define VRT_CL_ERSPL		30	/* CL.ERSmallPulseLaser */
#define VRT_CL_SLRM5		15	/* CL.StreakLRM-5 */
#define VRT_CL_SLRM10		20	/* CL.StreakLRM-10 */
#define VRT_CL_SLRM15		25	/* CL.StreakLRM-15 */
#define VRT_CL_SLRM20		30	/* CL.StreakLRM-20 */
#define VRT_IS_APOD		30	/* IS.A-Pod */
#define VRT_CL_HLL		30	/* CL.HeavyLargeLaser */
#define VRT_CL_HML		25	/* CL.HeavyMediumLaser */
#define VRT_CL_HSL		20	/* CL.HeavySmallLaser */
#define VRT_IS_INARC		30	/* IS.iNarcBeacon */
#define VRT_IS_RAC2		15	/* IS.RotaryAC/2 */
#define VRT_IS_RAC5		22	/* IS.RotaryAC/5 */
#define VRT_IS_HGR		30	/* IS.HeavyGaussRifle */
#define VRT_IS_MGR		12	/* IS.MagshotGaussRifle */
#define VRT_CL_MICROPL		15	/* CL.MicroPulseLaser */
#define VRT_IS_RL10		30	/* IS.RL-10 */
#define VRT_IS_RL15		30	/* IS.RL-15 */
#define VRT_IS_RL20		30	/* IS.RL-20 */
#define VRT_IS_COOLANTGUN   15  /* IS.CoolantGun */
#define VRT_IS_ACIDTHROWER  25  /* IS.AcidThrower */
